# file: postgresql/tasks/extensions/contrib.yml

- name: PostgreSQL | Extensions | Make sure the postgres repmgr extension is installed
  apt:
    name: "postgresql-{{postgresql_version}}-repmgr"
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  notify:
    - restart postgresql
